### ISSUE TITLE
[FEATURE] Set custom terminal and show symbolic links

### ISSUE THREAD

**Issue by Gaetan-LeGac** [lucaskenda/handyscripts2#2]
Hi, here is my proposal for two features:

- Ability to set a custom terminal command in the settings window, instead of `gnome-terminal` (ex: `tilix -e <command>`)
- In the popup, list script files **and** symbolic links to script files. It can be useful if, by example, we have a `/home/x/scripts` folder with a lot of scripts arranged in subfolders, and we want to put links to some of them in a `/home/x/scripts/handyscript` to run them easily from HandyScripts

What's your opinion on that ?

**Comment by lucaskenda** [comment]
Hi! Sorry for the delay...

- For the first proposal I've added a new field:

  ![image](https://user-images.githubusercontent.com/4048688/115128937-b5a12300-9fb7-11eb-8a53-83d497c5237e.png)

  So you can change the terminal, as long as the terminal can execute a command as parameter.
  **Gnome**: gnome-terminal --
  **Tilix**: tilix -e
  **KDE**: konsole -e
  
  The fix is still in revision, as soon as the Gnome Extensions admin aprove it you will see the changes.

- I've only made tests with files, not symbolic links, but this is a nice feature. I'll try to make it work for the next version.

Thanks!

**Comment by Gaetan-LeGac** [comment]
Great ! Thank you for studying my suggestions. 
Custom terminal command is working fine for me.
If I have some free time this week, I will also try to integrate symbolic links support.
